version: '3'
services:
  node-app:
    build: 
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app             #mount volume
      - /app/node_modules   #anonymous volume
    environment:
      - NODE_ENV=development
    command: npm run dev