version: '3'
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build: 
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app             #mount volume
      - /app/node_modules   #anonymous volume
    environment:
      - NODE_ENV=development
      - MONGO_USER=saujan
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=secret
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=saujan
      - MONGO_INITDB_ROOT_PASSWORD=mypassword